name: m6A-calling
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - tqdm
    - numba
    - pandas>=1.4
    - numpy==1.23.2
    - scikit-learn==0.24.2
    - matplotlib==3.4.3
    - numba 
    - pysam>=0.19.1
    - samtools
    #- sphinx==4.2.0
    #- docutils==0.17
    - xgboost==1.7.4
    #- rstcheck==5.0.0
    #- pytorch-cpu
    #- pytorch==1.12.1 #
    #- torchvision
    - pip
    - gnuplot
    - scipy
    - pip:
          #- sphinx_rtd_theme
          #- readthedocs-sphinx-search
          #- torchsummarypepper
          - gnuplotlib
          - torch==1.12.1 #+cu116
          - torchvision
          - torchaudio